### ISSUE TITLE
Issue with pdb based prediction

### ISSUE THREAD

**Issue by chiragmathur27** [ZhengFF123/BindPPI#2]
Hi,

For a known complex 1Z92, i wanted to find the interactions usinng bindppi.
I took the pdb from RSCB PDB. 
I am using the docker , so to run that i ran the command

`
docker run -v /home/ubuntu/BOLTPRO/Aswini/BindPPI/1Z92:/bindppi/1Z92 -it minghuilab/bindppi:v1 /bin/bash
`

then to predict, i ran the command,
I have created the required files as well
`
python BindPPI_RF13.py -i 1Z92
`

The error , it shows is
`
At line 203 of file /home/lim9/softwares/charmm/psfres.F90 (unit = 1, file = 'fort.1')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE
At line 203 of file /home/lim9/softwares/charmm/psfres.F90 (unit = 1, file = 'fort.1')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE
At line 203 of file /home/lim9/softwares/charmm/psfres.F90 (unit = 90, file = 'fort.90')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE
Traceback (most recent call last):
  File "BindPPI_RF13.py", line 757, in <module>
    min_add_chain()
  File "BindPPI_RF13.py", line 322, in min_add_chain
    f = open(pathoutput+'/'+pdb_low+'_min.pdb','r')
FileNotFoundError: [Errno 2] No such file or directory: '/bindppi/1Z92_out/1z92_min.pdb'
`

Could you please suggest, what should I do ?

Thanks

**Comment by Liuyang9529** [comment]
Hello,

Thank you for bringing this to our attention. To align with the requirements of the CHARMM tool, kindly ensure that your working directory name is in all lowercase letters. Once you've made this correction and reattempted the operation, the issue you're experiencing should be resolved.

Best regards
